In [25]:
import pandas as pd
employee = pd.read_csv("C:/ram/FALL/DMQL/project/EMployee.csv")

In [26]:
employee

,Employee_Id,Emp_Name,Email_Id,Phone,Branch_name,Branch_id
0,BSA76886793,Laurie Peck,laurie.peck@bsabank.com,+1(357) 798-4657,Depe,BOFABUF17
1,BSA59860024,Joel Webb,joel.webb@bsabank.com,+1(985) 895-5467,West Seneca,BOFABUF09
2,BSA46800944,Jordan Simpson,jordan.simpson@bsabank.com,+1(482) 545-8708,Fountain Plaza,BOFABUF01
3,BSA53277210,Jeffrey Barnes,jeffrey.barnes@bsabank.com,+1(668) 306-3490,Brierwood,BOFABUF19
4,BSA77775339,Allan Bell,allan.bell@bsabank.com,+1(538) 482-4191,Kenmore,BOFABUF12
...,...,...,...,...,...,...
245,BSA27703440,Charlotte Pearson,charlotte.pearson@bsabank.com,+1(575) 708-2663,Getzville,BOFABUF10
246,BSA76225705,Tina Willis,tina.willis@bsabank.com,+1(918) 946-2863,Depe,BOFABUF17
247,BSA45678507,Daisy Garrett,daisy.garrett@bsabank.com,+1(285) 741-4849,Fillmore,BOFABUF05
248,BSA39994906,Cathy Fisher,cathy.fisher@bsabank.com,+1(444) 707-5174,Fountain Plaza,BOFABUF01
249,BSA90728467,Darryl Wagner,darryl.wagner@bsabank.com,+1(920) 360-5451,Elmwood,BOFABUF02

In [27]:

Upd_branch_id=[]
for i in employee['Branch_id']:
    Upd_branch_id.append(i.replace("BOFA","BSA"))
    
    
Upd_emp_id=[]
for i in employee['Employee_Id']:
    Upd_emp_id.append(i.replace("BSA","E"))


    
employee=employee.drop(["Branch_name",'Employee_Id'],axis=1)
employee['Branch_id'] = Upd_branch_id


employee.insert(0, 'Employee_id', Upd_emp_id)

In [28]:
employee

,Employee_id,Emp_Name,Email_Id,Phone,Branch_id
0,E76886793,Laurie Peck,laurie.peck@bsabank.com,+1(357) 798-4657,BSABUF17
1,E59860024,Joel Webb,joel.webb@bsabank.com,+1(985) 895-5467,BSABUF09
2,E46800944,Jordan Simpson,jordan.simpson@bsabank.com,+1(482) 545-8708,BSABUF01
3,E53277210,Jeffrey Barnes,jeffrey.barnes@bsabank.com,+1(668) 306-3490,BSABUF19
4,E77775339,Allan Bell,allan.bell@bsabank.com,+1(538) 482-4191,BSABUF12
...,...,...,...,...,...
245,E27703440,Charlotte Pearson,charlotte.pearson@bsabank.com,+1(575) 708-2663,BSABUF10
246,E76225705,Tina Willis,tina.willis@bsabank.com,+1(918) 946-2863,BSABUF17
247,E45678507,Daisy Garrett,daisy.garrett@bsabank.com,+1(285) 741-4849,BSABUF05
248,E39994906,Cathy Fisher,cathy.fisher@bsabank.com,+1(444) 707-5174,BSABUF01
249,E90728467,Darryl Wagner,darryl.wagner@bsabank.com,+1(920) 360-5451,BSABUF02

In [31]:
employee.to_csv('Employee.csv')